language: csharp
mono: none
dotnet: 2.2
dist: xenial

jobs:
  include:
    - stage: "Initialize"
      script: dotnet --version
    - stage: "Build Templete Generator"
      script:
        - cd templete
        - dotnet new console
        - rm Program.cs
        - dotnet build
    - stage: "Build LeetCode && Test"
      script:
        - dotnet bulid
        - dotnet test
