language: csharp
dist: xenial

jobs:
  include:
    - stage: "Build"
      name: ".NET Core Bulid"
      dotnet: 2.2
      mono: none
      script:
        - cd templete && dotnet new console && rm Program.cs && dotnet build && cd ..
        - dotnet test
    - name: "Mono Build"
      mono: latest
      install:
        - nuget restore LeetCode.csproj
        - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release
        - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./bin/Release/LeetCode.dll
