language: csharp
dist: xenial
notifications:
  email: false

jobs:
  include:
    - stage: "Build"
      name: ".NET Core Bulid"
      dotnet: 2.2
      mono: none
      script:
        - cd templete && dotnet new console && rm Program.cs && dotnet build && cd ..
        - dotnet test
    - name: "Mono Build"
      mono: latest
      before_install:
        - sed -i 's/netcoreapp2.2/netcoreapp2.1/' LeetCode.csproj
        - sed -i 'i19 <PackageReference Include="System.Memory" />' LeetCode.csproj
      install:
        - nuget restore LeetCode.csproj
        # - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
        - nuget install xunit.runner.console
      script:
        # - msbuild /p:Configuration=Debug
        # - mono ./xunit.runner.console.2.4.1/tools/netcoreapp2.0/xunit.console.dll ./bin/Debug/netcoreapp2.1/LeetCode.dll
        - cat LeetCode.csproj
        - msbuild /t:Publish
        - mono ./xunit.runner.console.2.4.1/tools/net472/xunit.console.exe ./bin/Debug/netcoreapp2.1/publish/LeetCode.dll

